name: project_judge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  dio: ^5.7.0
  get_storage: ^2.1.1
  flutter_bloc: ^8.1.6
  pinput: ^5.0.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  device_preview: ^1.2.0
  date_picker_plus: ^4.1.0
  image_picker: ^1.1.2
  image_picker_platform_interface: ^2.10.0
  file_picker: ^8.1.2
  pdf_viewer_plugin: ^2.0.1
  intl: ^0.19.0
  simple_icons: ^10.1.3
  carousel_slider: ^5.0.0
  expansion_tile_card: ^3.0.0
  flutter_rating_bar: ^4.0.1
  circular_countdown_timer: ^0.2.4
  url_launcher: ^6.3.0
  flutter_webview_plugin: ^0.4.0
  webview_flutter: ^4.9.0
  open_filex: ^4.5.0
  uri_to_file: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/json/
    - assets/images/
    - assets/svg/
    - assets/gif/
