name: project_judge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  dio: ^5.7.0
  get_storage: ^2.1.1
  flutter_bloc: ^8.1.6
  pinput: ^5.0.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  device_preview: ^1.2.0
  date_picker_plus: ^4.1.0
  image_picker: ^1.1.2
  image_picker_platform_interface: ^2.10.0
  file_picker: ^8.1.2
  pdf_viewer_plugin: ^2.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/json/
    - assets/images/
    - assets/svg/
